baseURL: https://aztroop201.github.io/aztroop201-website/
languageCode: en-us
footnoteReturnLinkContents: â†©
params:
  AuthorName: Sean Bridges
  GitHubUser: shizeon
  ListOfFoo:
  - foo1
  - foo2
  SidebarRecentLimit: 5
  Subtitle: Troop 201 Subtitle, where does this show
  custom_css:
  - css/custom.css
  favicon: favicon/favicon.ico
  # permalinks:
  #   posts: /:year/:month/:title/
title: Boy Scouts Troop 201
copyright: Troop 201 -
theme: ananke
markup:
  goldmark:
    renderer:
      unsafe: true
site_logo: